### ISSUE TITLE
Improvement Suggestion - Make sure to directly being able to add something in front of the drafted commit message

### ISSUE THREAD

**Issue by Steff81** [jnsahaj/lumen#14]
Backgound:
We need in the commit message at the very beginning always the corresponding JIRA Issue No. 
At the moment it is possible to manually edit the drafted message with 
   lumen draft | git commit -e -F -
and then add the JIRA Issue there. This is ok.

But it would be better to have the option to directly add a string that is put in front of the AI generated text and commit it directly like this:
lumen draft -x "JIRA-1234" | git commit -F -

So the commit message could then be: 
JIRA-1234 Update CSS styles and HTML structure for maintenance page

Maybe someone else also have the need to put something directly in front of the commit message :)

**Comment by jnsahaj** [comment]
Interesting idea, however I don't think this lies in the scope of this project. 
Since lumen outputs a string to stdout, you can simply use `sed`

```
lumen draft | sed 's/^/prefix_text /' | git commit -F -
```

Once you have figured out your workflow, you can always make a script

```sh
# .bashrc / .zshrc
aicommit() {
  prefix="$1"
  shift
  lumen draft "$@" | sed "s/^/${prefix} /" | git commit -e -F -
}
```

This will allow you to use it like
```
aicommit "JIRA-123-" -c "my context"
```
