### ISSUE TITLE
Support for ollama

### ISSUE THREAD

**Issue by BaptisteRoseau** [jnsahaj/lumen#7]
I would be great to add support for https://ollama.com/

That way we could use models 100% locally, and Ollama is becoming a standard.

The API documentation can be found here: https://github.com/ollama/ollama/blob/main/docs/api.md

For example, to get a response you would do something like:

```
curl http://127.0.0.1:11434/api/chat -d '{
  "model": "llama3.2:1b",
  "messages": [
    {
      "role": "user",
      "content": "Summarize this commit"
    }
  ],
  "stream": false
}'
{"model":"llama3.2:1b","created_at":"2024-11-06T13:16:01.684646358Z","message":{"role":"assistant","content":"I'm not aware of any information about a specific commit. Could you please provide more context or details about the commit you're referring to?"},"done_reason":"stop","done":true,"total_duration":1364881190,"load_duration":22355595,"prompt_eval_count":30,"prompt_eval_duration":74193000,"eval_count":29,"eval_duration":1225722000}
```

Seems like there is an Ollama rust crate but I don't know how useful it can be to you: https://docs.rs/ollama-rs/latest/ollama_rs/#

In lumen's CLI we could add:

- The model name
- The root URL of ollama (default `http://127.0.0.1:11434/`)

Hope these information will help!

**Comment by jnsahaj** [comment]
Hey 👋 
Thanks for the detailed information.

I think I can implement this quite easily, however I don't have the required hardware to run a model locally to test it.

Would it be possible for you to test a pre-release version of the same to see if it's working fine?

**Comment by jnsahaj** [comment]
I will merge the PR if it works
Let me know if you need any help to get started

Need to test for these scenarios
1. cargo r -- -p "ollama" -m "your-model" explain HEAD
2. cargo r -- -p "ollama" -m "your-model" draft
3. cargo r -- -p "ollama" -m "invalid-model" explain HEAD

**Comment by BaptisteRoseau** [comment]
Works like a charm, however the display in terminal shows plain `\n` instead of converting them to line skip.

```
baptiste:/tmp/lumen (feature/support-ollama)$ time cargo r -- -p "ollama" -m "llama3.2:3b" explain HEAD
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/lumen -p ollama -m 'llama3.2:3b' explain HEAD`
# Entity: Commit
`commit b50664a92b957e782e09ab02749fff1605302a56` | Sahaj Jain <sahajjain13@gmail.com> | 2024-11-06 22:06:54

feat(provider): Add Ollama support
-----

✓ Done
"**Commit Explanation**\n=====================\n\n### Core Changes Made\n\n*   Introduced the Ollama provider, adding support for OpenAI's Ollama model.\n*   Created new files `src/provider/ollama.rs` and updated existing code to handle the new provider.\n\n### Direct Impact\n\n*   Users can now use the Ollama provider to interact with Ollama models, enabling them to leverage Ollama's capabilities in their projects."

real    0m9,129s
user    0m0,120s
sys     0m0,045s
```

I just added "Adding some stuff in README just for testing sake" in the README.md, the commit message is wrong but your PR works. I wonder if it is possible to give a custom prompt to guide the AI on how to interpret the git diff.

```
baptiste:/tmp/lumen (feature/support-ollama)$ nano README.md
baptiste:/tmp/lumen (feature/support-ollama)$ git add README.md
baptiste:/tmp/lumen (feature/support-ollama)$ time cargo r -- -p "ollama" -m "llama3.2:3b" draft
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/lumen -p ollama -m 'llama3.2:3b' draft`
"refactor(ci): Remove unnecessary sections from README.md"
real    0m9,278s
user    0m0,113s
sys     0m0,033s
```

```
baptiste:/tmp/lumen (feature/support-ollama)$ time cargo r -- -p "ollama" -m "invalid-model" explain HEAD
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/lumen -p ollama -m invalid-model explain HEAD`
# Entity: Commit
`commit b50664a92b957e782e09ab02749fff1605302a56` | Sahaj Jain <sahajjain13@gmail.com> | 2024-11-06 22:06:54

feat(provider): Add Ollama support
-----

error: API request failed with status code 404 Not Found: response: {"error":"model \"invalid-model\" not found, try pulling it first"}

real    0m0,152s
user    0m0,106s
sys     0m0,049s
```

For reference, llama3.2:3b only take 4GB of VRAM so you might be able to use it as well:

```
baptiste:/tmp/lumen (feature/support-ollama)$ ollama ps
NAME           ID              SIZE      PROCESSOR    UNTIL
llama3.2:3b    a80c4f17acd5    4.0 GB    100% GPU     2 minutes from now
```

Edit: For testing purposes if you want to try on your side you can install Ollama or run it with Docker and use the llama3.2:1b model which is even smaller. If only for API testing it should work just fine :D

**Comment by jnsahaj** [comment]
Appreciate the analysis
> however the display in terminal shows plain \n instead of converting them to line skip.

Oversight on my part, fixed

> the commit message is wrong but your PR works

They said AI generated commit messages will save you time. Jokes apart, I think it should work better with real usecases. The free model is admittedly wonky

>  I wonder if it is possible to give a custom prompt to guide the AI on how to interpret the git diff.

I noticed this too, which is why I had just released the "context" thing today
So you can say `lumen draft -c "improve perf"` and it will now generate the message based on the changes accounting for your intent. Check README for more details

**Comment by BaptisteRoseau** [comment]
Thank you for this new feature, appreciate it :D

**Comment by r4vi** [comment]
confirmed working for me with -p ollama -m "llama3.1"
